name: ubunturdp
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'aditya'
        required: true
        default: 'paste your code here'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Creating User to Login
      run: echo "user:root@0" | sudo chpasswd && wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && chmod +x ngrok && ./ngrok authtoken 23vAgNYXuCWyFzltBzLRjeaPsUy_V5GWt1TYC6LvLHHcixjU && ./ngrok tcp 22

